- color_helper.sublime-settings
Fixed minor grammar issue.
Thanks you for contributing to this project!  Make sure you've read: http://facelessuser.github.io/ColorHelper/contributing/.  Please follow the guidelines below.
- Please describe the change in as much detail as possible so I can understand what is being added or modified.
- If you are solving a bug that does not already have an issue, please describe the bug in detail and provide info on how to reproduce if applicable (this is good for me and others to reference later when verifying the issue has been resolved).
- Please reference and link related open bugs or feature requests in this pull if applicable.
- Make sure you've documented or updated the existing documentation if introducing a new feature or modifying the behavior of an existing feature that a user …
> Fixed typo

- color_helper.py
Don't overwrite the project palettes with new variable. Fixes #111
> Fix project palettes

- color_helper.py
- color_helper_picker.py
> Reduce borders and in some cases remove borders

- color_helper.py
> Allow insert when there is an active selection

- color_helper.sublime-settings
> Fix SCSS and Sass

- color_helper.py
- color_helper.sublime-settings
- color_helper_picker.py
- docs/src/markdown/usage.md
> Add minimum height cap when dealing with image sizes and allow better scaling

- .pyspelling.yml
- CHANGES.md
- color_helper_util.py
- docs/src/dictionary/en-custom.txt
- lib/rgba.py
- messages.json
- messages/recent.md
- support.py
- HSL can support alpha channels as hsl or hsla (per the CSS spec)
- HSL and HWB can support units deg, turn, rad, grad
> Color enhancements

- CHANGES.md
- color_helper.py
- color_helper.sublime-settings
- docs/src/markdown/usage.md
- support.py
> Use blocklist and allowlist instead of blacklist and whitelist

- CHANGES.md
- color_helper.py
- color_helper.sublime-settings
- color_helper_insert.py
- color_helper_util.py
- messages.json
- messages/install.md
- messages/recent.md
- panels/color-picker.html
- panels/info.html
- panels/insert.html
- support.py
> Add support for CSS Color Level 4 HSL, RGB, and HWB

- color_helper_preview.py
> Use WindowCommand for previews to fix breakage of find highlight

- CHANGES.md
- color_helper.sublime-settings
- color_helper_util.py
- docs/src/markdown/settings/rules.md
> Ignore color key words when they are preceeded by `$` (SCSS)

- CHANGES.md
- color-helper-colors.sublime-syntax
- color_helper.py
- color_helper_picker.py
- color_helper_tools.py
- color_helper_util.py
- examples/test.css
- panels/color-picker.html
- panels/colors.html
- panels/info.html
- panels/insert.html
- panels/palettes.html
- panels/tools.html
- Improved visuals for popups and `TextInputHandlers`. Improve consistency in how things are presented.
- Fix a few transitions between different popups.
> Add some spit and polish to UI stuff

- CHANGES.md
- ch_preview.py
> Fix issue with duplicate previews in clone view

- .github/CONTRIBUTING.md
Edit to provide the correct link (the previous link led to a 404 error).
Thanks you for contributing to this project!  Make sure you've read: http://facelessuser.github.io/ColorHelper/contributing/.  Please follow the guidelines below.
- Please describe the change in as much detail as possible so I can understand what is being added or modified.
- If you are solving a bug that does not already have an issue, please describe the bug in detail and provide info on how to reproduce if applicable (this is good for me and others to reference later when verifying the issue has been resolved).
- Please reference and link related open bugs or feature requests in this pull if applicable.
- Make sure you've documented or updated the existing documentation if introducing a new feature or modifying …
> Fix 404 error in CONTRIBUTING.md

- CHANGES.md
- color_helper.sublime-settings
- custom/ahex.py
- custom/ass_abgr.py
- custom/hex_0x.py
- custom/tmtheme.py
- messages.json
- messages/recent.md
- support.py
Resolves #209
Thanks you for contributing to this project!  Make sure you've read: http://facelessuser.github.io/ColorHelper/contributing/.  Please follow the guidelines below.
- Please describe the change in as much detail as possible so I can understand what is being added or modified.
- If you are solving a bug that does not already have an issue, please describe the bug in detail and provide info on how to reproduce if applicable (this is good for me and others to reference later when verifying the issue has been resolved).
- Please reference and link related open bugs or feature requests in this pull if applicable.
- Make sure you've documented or updated the existing documentation if introducing a new feature or modifying the behavior of an existing feature that a user needs to be …
> Add graphviz support

- CHANGES.md
- ch_util.py
- support.py
Fixes #211
Thanks you for contributing to this project!  Make sure you've read: http://facelessuser.github.io/ColorHelper/contributing/.  Please follow the guidelines below.
- Please describe the change in as much detail as possible so I can understand what is being added or modified.
- If you are solving a bug that does not already have an issue, please describe the bug in detail and provide info on how to reproduce if applicable (this is good for me and others to reference later when verifying the issue has been resolved).
- Please reference and link related open bugs or feature requests in this pull if applicable.
- Make sure you've documented or updated the existing documentation if introducing a new feature or modifying the behavior of an existing feature that a user needs to be …
> Fix version handling

- .github/PULL_REQUEST_TEMPLATE.md
- color_helper.sublime-settings
- docs/src/markdown/settings/color_picker.md
* Fix a few spelling errors
* Fix URL in `.github/PULL_REQUEST_TEMPLATE.md`
* Minor copyedits
> [Chore] Spelling; copyedit

- CHANGES.md
- ch_preview.py
- messages.json
- messages/recent.md
- support.py
> Fix exception in preview when view has no syntax

- CHANGES.md
- ch_preview.py
- color_helper.sublime-settings
- docs/src/markdown/settings/previews.md
- messages/recent.md
> Add preview window padding config and run on window activation

- docs/src/markdown/about/contributing.md
- docs/src/markdown/faq.md
- docs/src/markdown/index.md
- docs/src/markdown/installation.md
- docs/src/markdown/settings/previews.md
- docs/src/markdown/settings/rules.md
- docs/src/markdown/usage.md
- mkdocs.yml
> Documentation updates

- color_helper.sublime-settings
- docs/src/markdown/settings/previews.md
Fixes #257. Probably a minor semver bump - I wasn't sure.
> Do not pad sliding preview window by default

- CHANGES.md
- lib/coloraide/algebra.py
- lib/coloraide/gamut/fit_lch_chroma.py
- lib/coloraide/spaces/cmy.py
- lib/coloraide/spaces/cmyk.py
- lib/coloraide/spaces/prismatic.py
- lib/coloraide/spaces/ryb.py
- lib/coloraide/spaces/srgb/__init__.py
- lib/coloraide/spaces/xyy.py
- lib/coloraide/spaces/xyz_d65.py
- mkdocs.yml
- support.py
> Fix missing math.isclose

- color_helper.sublime-settings
> Add color rule for INI syntax

- CHANGES.md
- ch_picker.py
- messages/recent.md
- support.py
> Fix issue with API update
